// Comprehensive Mock Data for DAO Registry
// Uses all JSON key slots for testing

const comprehensiveMockDAOs = [
  {
    id: '1',
    name: 'Uniswap DAO',
    symbol: 'UNI',
    description: 'Decentralized exchange governance protocol',
    contractAddress: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    tokenAddress: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    treasuryAddress: '0x4750c43867EF5F89869132eccf19B9b6C4280E09',
    governanceAddress: '0x5e4be8Bc9637f0EAA1A755069e05802F9a6C424a',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 7,
    quorum: 40000000,
    proposalThreshold: 10000000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user1',
    tags: ['DeFi', 'DEX', 'Governance', 'Liquidity', 'ISO23081', 'RFC001', 'RFC004', 'ENS', 'Analytics'],
    logo: 'https://assets.uniswap.org/logo.png',
    website: 'https://uniswap.org',
    ensDomain: 'uniswap.eth',
    ensSubdomains: {
      governance: 'gov.uniswap.eth',
      treasury: 'treasury.uniswap.eth',
      forum: 'forum.uniswap.eth',
      analytics: 'analytics.uniswap.eth'
    },
    ensMetadata: {
      description: 'Uniswap DAO official ENS domain',
      url: 'https://uniswap.eth',
      avatar: 'https://assets.uniswap.org/avatar.png',
      email: 'contact@uniswap.eth',
      notice: 'Official Uniswap DAO ENS',
      keywords: 'dex, defi, governance, liquidity',
      'com.twitter': 'Uniswap',
      'com.github': 'Uniswap',
      'org.telegram': 'UniswapDAO'
    },
    socialLinks: {
      twitter: 'https://twitter.com/Uniswap',
      discord: 'https://discord.gg/uniswap',
      github: 'https://github.com/Uniswap',
      medium: 'https://medium.com/uniswap',
      reddit: 'https://reddit.com/r/uniswap',
      telegram: 'https://t.me/uniswap',
      email: 'contact@uniswap.eth'
    },
    metadata: {
      recordId: 'dao-1',
      systemId: 'dao-registry-mainnet',
      externalId: 'uniswap-eth',
      recordType: 'DAO',
      securityClassification: 'public',
      accessRights: 'open',
      creator: { id: 'user1', type: 'user', name: 'Uniswap Foundation' },
      creationDate: '2021-05-01T00:00:00Z',
      creationMethod: 'manual',
      title: 'Uniswap DAO',
      subject: ['DeFi', 'DEX', 'Governance'],
      abstract: 'Uniswap DAO is a decentralized protocol for automated liquidity provision on Ethereum.',
      keywords: ['uniswap', 'dex', 'liquidity', 'governance', 'ethereum'],
      language: 'en',
      format: 'application/json',
      encoding: 'utf-8',
      fileSize: 2048,
      checksum: 'sha256-abcdef1234567890',
      mimeType: 'application/json',
      accessHistory: [
        { userId: 'user1', timestamp: '2024-01-01T12:00:00Z', action: 'view' },
        { userId: 'user2', timestamp: '2024-01-02T13:00:00Z', action: 'edit' }
      ],
      usageRights: 'open',
      retentionSchedule: 'permanent',
      businessFunction: 'liquidity provision',
      businessProcess: 'automated market making',
      businessActivity: 'exchange',
      systemEnvironment: 'Ethereum Mainnet',
      applicationSoftware: 'Uniswap v3',
      hardwarePlatform: 'cloud',
      scheduledEvents: [
        { event: 'annual audit', date: '2024-12-31' }
      ],
      triggerConditions: ['governance proposal passed'],
      actionPlans: ['distribute rewards'],
      businessRules: ['must maintain 10% quorum'],
      complianceRequirements: ['ISO23081'],
      retentionPolicies: ['permanent'],
      events: [
        { type: 'proposal', id: 'prop-1', date: '2024-01-10' },
        { type: 'vote', id: 'vote-1', date: '2024-01-11' }
      ],
      eventTypes: ['proposal', 'vote']
    },
    createdAt: new Date('2021-05-01'),
    updatedAt: new Date('2024-01-15')
  },
  {
    id: '2',
    name: 'Aave DAO',
    symbol: 'AAVE',
    description: 'Decentralized lending protocol governance',
    contractAddress: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
    tokenAddress: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
    treasuryAddress: '0x25F2226B597E8F9514B3F68F00f510cEfD2D811c',
    governanceAddress: '0xEC568fffba86c094cf06b22134B23074DFE2252c',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 5,
    quorum: 800000,
    proposalThreshold: 80000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user2',
    tags: ['DeFi', 'Lending', 'Governance', 'Yield'],
    socialLinks: {
      twitter: 'https://twitter.com/AaveAave',
      discord: 'https://discord.gg/aave',
      github: 'https://github.com/aave',
      medium: 'https://medium.com/aave',
      telegram: 'https://t.me/Aavesome'
    },
    createdAt: new Date('2020-12-01'),
    updatedAt: new Date('2024-01-10')
  },
  {
    id: '3',
    name: 'Compound DAO',
    symbol: 'COMP',
    description: 'Algorithmic interest rate protocol governance',
    contractAddress: '0xc00e94Cb662C3520282E6f5717214004A7f26888',
    tokenAddress: '0xc00e94Cb662C3520282E6f5717214004A7f26888',
    treasuryAddress: '0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B',
    governanceAddress: '0x6d903f6003ba625cd163582c4e4a27f2b91bd6f8',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 3,
    quorum: 400000,
    proposalThreshold: 100000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user3',
    tags: ['DeFi', 'Lending', 'Governance', 'Interest'],
    socialLinks: {
      twitter: 'https://twitter.com/compoundfinance',
      discord: 'https://discord.gg/compound',
      github: 'https://github.com/compound-finance',
      medium: 'https://medium.com/compound-finance'
    },
    createdAt: new Date('2020-06-15'),
    updatedAt: new Date('2024-01-05')
  },
  {
    id: '4',
    name: 'Maker DAO',
    symbol: 'MKR',
    description: 'Decentralized stablecoin governance',
    contractAddress: '0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2',
    tokenAddress: '0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2',
    treasuryAddress: '0xBE8E3e3618f7474F8cB1d074A26afFef007E98FB',
    governanceAddress: '0x0a59649758cA4D0fD0157FfcdcD608134C11f653',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 3,
    quorum: 100000,
    proposalThreshold: 1000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user4',
    tags: ['DeFi', 'Stablecoin', 'Governance', 'Dai'],
    socialLinks: {
      twitter: 'https://twitter.com/MakerDAO',
      discord: 'https://discord.gg/makerdao',
      github: 'https://github.com/makerdao',
      medium: 'https://medium.com/makerdao',
      reddit: 'https://reddit.com/r/MakerDAO'
    },
    createdAt: new Date('2019-11-18'),
    updatedAt: new Date('2024-01-12')
  },
  {
    id: '5',
    name: 'Curve DAO',
    symbol: 'CRV',
    description: 'Decentralized exchange for stablecoins',
    contractAddress: '0xD533a949740bb3306d119CC777fa900bA034cd52',
    tokenAddress: '0xD533a949740bb3306d119CC777fa900bA034cd52',
    treasuryAddress: '0x745116Ea696e612258e5bC146f5AA1fEBd751765',
    governanceAddress: '0xE478de485ad2fe9d31c2c8b8b8b8b8b8b8b8b8b8',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 3,
    quorum: 30000000,
    proposalThreshold: 2500000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user5',
    tags: ['DeFi', 'DEX', 'Governance', 'Stablecoin'],
    socialLinks: {
      twitter: 'https://twitter.com/curvefinance',
      discord: 'https://discord.gg/curve',
      github: 'https://github.com/curvefi',
      medium: 'https://medium.com/curve-finance'
    },
    createdAt: new Date('2020-08-14'),
    updatedAt: new Date('2024-01-08')
  },
  {
    id: '6',
    name: 'Synthetix DAO',
    symbol: 'SNX',
    description: 'Decentralized synthetic asset protocol',
    contractAddress: '0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F',
    tokenAddress: '0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F',
    treasuryAddress: '0x99F4176EE457afed2F6C8b1Ea1B0B4C1c19B8C8C',
    governanceAddress: '0x813328d6C5619834B7856b8b8b8b8b8b8b8b8b8b',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 7,
    quorum: 5000000,
    proposalThreshold: 1000000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user6',
    tags: ['DeFi', 'Synthetic', 'Governance', 'Derivatives'],
    socialLinks: {
      twitter: 'https://twitter.com/synthetix_io',
      discord: 'https://discord.gg/synthetix',
      github: 'https://github.com/synthetixio',
      medium: 'https://medium.com/synthetix'
    },
    createdAt: new Date('2019-03-15'),
    updatedAt: new Date('2024-01-03')
  },
  {
    id: '7',
    name: 'Yearn Finance DAO',
    symbol: 'YFI',
    description: 'Decentralized yield aggregator',
    contractAddress: '0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e',
    tokenAddress: '0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e',
    treasuryAddress: '0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52',
    governanceAddress: '0x90E00ACe148ca3b23Ac1bC8C240C2a7Dd9c2d7f5',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 3,
    quorum: 1000,
    proposalThreshold: 1,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user7',
    tags: ['DeFi', 'Yield', 'Governance', 'Aggregator'],
    socialLinks: {
      twitter: 'https://twitter.com/iearnfinance',
      discord: 'https://discord.gg/yearn',
      github: 'https://github.com/yearn',
      medium: 'https://medium.com/iearn'
    },
    createdAt: new Date('2020-07-17'),
    updatedAt: new Date('2024-01-01')
  },
  {
    id: '8',
    name: 'Balancer DAO',
    symbol: 'BAL',
    description: 'Decentralized automated market maker',
    contractAddress: '0xba100000625a3754423978a60c9317c58a424e3D',
    tokenAddress: '0xba100000625a3754423978a60c9317c58a424e3D',
    treasuryAddress: '0x10A19e7eE7d7F8a52822f6817de8ea18244FcEA7',
    governanceAddress: '0x5c6E30439D1712497C97A8A28a0c8f6F64f4Ba41',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 7,
    quorum: 500000,
    proposalThreshold: 50000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user8',
    tags: ['DeFi', 'AMM', 'Governance', 'Liquidity'],
    socialLinks: {
      twitter: 'https://twitter.com/BalancerLabs',
      discord: 'https://discord.gg/balancer',
      github: 'https://github.com/balancer-labs',
      medium: 'https://medium.com/balancer-protocol'
    },
    createdAt: new Date('2020-06-01'),
    updatedAt: new Date('2024-01-07')
  },
  {
    id: '9',
    name: 'SushiSwap DAO',
    symbol: 'SUSHI',
    description: 'Decentralized exchange and yield farming',
    contractAddress: '0x6B3595068778DD592e39A122f4f5a5cF09C90fE2',
    tokenAddress: '0x6B3595068778DD592e39A122f4f5a5cF09C90fE2',
    treasuryAddress: '0x5a6A4D54456819380173272A5E8E9B5904c61D713',
    governanceAddress: '0x9B2f065400b63d3f3D2B3cA36aA3A0b4b7a5b5b5b',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 5,
    quorum: 5000000,
    proposalThreshold: 1000000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user9',
    tags: ['DeFi', 'DEX', 'Governance', 'Yield'],
    socialLinks: {
      twitter: 'https://twitter.com/sushiswap',
      discord: 'https://discord.gg/sushiswap',
      github: 'https://github.com/sushiswap',
      medium: 'https://medium.com/sushiswap'
    },
    createdAt: new Date('2020-08-28'),
    updatedAt: new Date('2024-01-09')
  },
  {
    id: '10',
    name: '1inch DAO',
    symbol: '1INCH',
    description: 'Decentralized exchange aggregator',
    contractAddress: '0x111111111117dC0aa78b770fA6A738034120C302',
    tokenAddress: '0x111111111117dC0aa78b770fA6A738034120C302',
    treasuryAddress: '0x1c4b70d8e6c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0',
    governanceAddress: '0x2c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0',
    chainId: 1,
    governanceType: 'TokenWeighted',
    votingPeriod: 7,
    quorum: 10000000,
    proposalThreshold: 1000000,
    status: 'Active',
    verified: true,
    active: true,
    ownerId: 'user10',
    tags: ['DeFi', 'Aggregator', 'Governance', 'DEX'],
    socialLinks: {
      twitter: 'https://twitter.com/1inch',
      discord: 'https://discord.gg/1inch',
      github: 'https://github.com/1inch',
      medium: 'https://medium.com/1inch-network'
    },
    createdAt: new Date('2020-12-25'),
    updatedAt: new Date('2024-01-11')
  }
];

const comprehensiveReservedSubdomains = new Map([
  // Priority 1: Critical system subdomains (10 entries)
  ['www', { priority: 1, category: 'system', description: 'World Wide Web', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['api', { priority: 1, category: 'system', description: 'Application Programming Interface', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['admin', { priority: 1, category: 'system', description: 'Administrative interface', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['mail', { priority: 1, category: 'system', description: 'Email services', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['ftp', { priority: 1, category: 'system', description: 'File Transfer Protocol', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['ssh', { priority: 1, category: 'system', description: 'Secure Shell', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['dns', { priority: 1, category: 'system', description: 'Domain Name System', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['ns', { priority: 1, category: 'system', description: 'Name Server', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['mx', { priority: 1, category: 'system', description: 'Mail Exchange', allowedFor: ['system'], restrictions: ['blocked'] }],
  ['smtp', { priority: 1, category: 'system', description: 'Simple Mail Transfer Protocol', allowedFor: ['system'], restrictions: ['blocked'] }],
  
  // Priority 2: Common web services (10 entries)
  ['blog', { priority: 2, category: 'web', description: 'Blogging platform', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['shop', { priority: 2, category: 'web', description: 'E-commerce platform', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['store', { priority: 2, category: 'web', description: 'Online store', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['app', { priority: 2, category: 'web', description: 'Web application', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['docs', { priority: 2, category: 'web', description: 'Documentation', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['help', { priority: 2, category: 'web', description: 'Help and support', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['support', { priority: 2, category: 'web', description: 'Customer support', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['status', { priority: 2, category: 'web', description: 'Service status', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['cdn', { priority: 2, category: 'web', description: 'Content Delivery Network', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  ['assets', { priority: 2, category: 'web', description: 'Static assets', allowedFor: ['verified'], restrictions: ['approval_required'] }],
  
  // Priority 3: Brand and trademark terms (10 entries)
  ['google', { priority: 3, category: 'brand', description: 'Google brand', allowedFor: ['google'], restrictions: ['trademark'] }],
  ['facebook', { priority: 3, category: 'brand', description: 'Facebook brand', allowedFor: ['facebook'], restrictions: ['trademark'] }],
  ['twitter', { priority: 3, category: 'brand', description: 'Twitter brand', allowedFor: ['twitter'], restrictions: ['trademark'] }],
  ['amazon', { priority: 3, category: 'brand', description: 'Amazon brand', allowedFor: ['amazon'], restrictions: ['trademark'] }],
  ['apple', { priority: 3, category: 'brand', description: 'Apple brand', allowedFor: ['apple'], restrictions: ['trademark'] }],
  ['microsoft', { priority: 3, category: 'brand', description: 'Microsoft brand', allowedFor: ['microsoft'], restrictions: ['trademark'] }],
  ['netflix', { priority: 3, category: 'brand', description: 'Netflix brand', allowedFor: ['netflix'], restrictions: ['trademark'] }],
  ['spotify', { priority: 3, category: 'brand', description: 'Spotify brand', allowedFor: ['spotify'], restrictions: ['trademark'] }],
  ['uber', { priority: 3, category: 'brand', description: 'Uber brand', allowedFor: ['uber'], restrictions: ['trademark'] }],
  ['airbnb', { priority: 3, category: 'brand', description: 'Airbnb brand', allowedFor: ['airbnb'], restrictions: ['trademark'] }],
  
  // Priority 4: Generic terms and common words (10 entries)
  ['test', { priority: 4, category: 'generic', description: 'Testing environment', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['demo', { priority: 4, category: 'generic', description: 'Demonstration', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['dev', { priority: 4, category: 'generic', description: 'Development environment', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['staging', { priority: 4, category: 'generic', description: 'Staging environment', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['beta', { priority: 4, category: 'generic', description: 'Beta version', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['alpha', { priority: 4, category: 'generic', description: 'Alpha version', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['new', { priority: 4, category: 'generic', description: 'New features', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['old', { priority: 4, category: 'generic', description: 'Legacy content', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['mobile', { priority: 4, category: 'generic', description: 'Mobile version', allowedFor: ['all'], restrictions: ['monitoring'] }],
  ['desktop', { priority: 4, category: 'generic', description: 'Desktop version', allowedFor: ['all'], restrictions: ['monitoring'] }]
]);

module.exports = {
  comprehensiveMockDAOs,
  comprehensiveReservedSubdomains
}; 